import { fetchGraphQL } from '@/lib/wordpress';
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from '@/components/Header';
import Footer from '@/components/Footer';


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const data = await fetchGraphQL(`
{
  generalSettings {
    title
  }
  menu(id: "main-menu", idType: SLUG) {
    menuItems {
      nodes {
        label
        path
      }
    }
  }
}
`);

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <Header
          siteTitle={data.generalSettings.title}
          menuItems={data.menu.menuItems.nodes}
        />

        {children}

        <Footer />

      </body>
    </html>
  );
}
